import os

ENV = os.environ["ENV"]

DB_CONFIG = {
    "SQLALCHEMY_DATABASE_URI": os.environ["DATABASE_URL"],
    "SQLALCHEMY_TRACK_MODIFICATIONS": False
}

AWS_BUCKET_NAME = os.environ["AWS_BUCKET_NAME"]

SENDER_EMAIL = os.environ["SENDER_EMAIL"]

GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
GOOGLE_AUTH_FALLBACK_URL = os.environ["GOOGLE_AUTH_FALLBACK_URL"]
