version: "2.1"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - ${HOME}/.aws:/usr/local/airflow/.aws # copy aws credentials from host to container
    env_file:
      - ./.env

  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: printmob
