version: "2.1"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
        - TZ=America/Argentina/Buenos_Aires

  cronjobs:
    build:
      context: .
      dockerfile: cronjobs.Dockerfile
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
        - TZ=America/Argentina/Buenos_Aires

  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: printmob
